# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - virtualenv venv
  - source venv/bin/activate

# tags make sure correct public gitlab runner is picked
test:
  script:
    - export PIP_EXTRA_INDEX_URL=https://artifactory.ing.net/artifactory/api/pypi/pypipublic/simple
    - export PIP_TRUSTED_HOST=artifactory.ing.net
    - pip install --upgrade setuptools
    - pip install ".[all]"
    - pytest --cov=skorecard/ --cov-config=.coveragerc --cov-report term-missing tests/
    - mypy --ignore-missing-imports --pretty --show-error-codes --namespace-packages -p skorecard
    - flake8 --max-line-length=120 --docstring-convention=google --ignore=D100,D104,D212,D200,E203,W293,D412,W503 skorecard
  tags:
    - dare
    - python
    - charmander
