repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      language_version: python3.6
      args: [--line-length=120]
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
      args: [--ignore-missing-imports, --pretty, --show-error-codes, --namespace-packages]
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [--max-line-length=120, --docstring-convention=google, --ignore=D100]
# D100 requires all Python files (modules) to have a "public" docstring even if all functions within have a docstring.
